project_id = "dhafduzlhpartlvsgbqx"

[functions.fms-validate]
verify_jwt = false

[functions.fms-admin-password]
verify_jwt = false

[functions.fms-stock-order]
verify_jwt = false

[functions.sign-contract]
verify_jwt = false

